### ISSUE TITLE
Add To Hub Requirements 

### ISSUE THREAD

**Issue by justinmerrell** [huggingface/hf_transfer#21]
I'm not sure if this issue belongs here or within the repos that `hf_transfer` is used. I am raising the issue here as it is more likely to get attention. 

Issue:

- ReadMe implies that `hf_transfer` is installed by default by supporting packages. 

Solution: 

- Add `hf_transfer` as a requirement to `huggingface_hub` and other repos that can make use of it. This will allow this repo to be used by setting the env var and not having to perform additional installations.

**Comment by McPatate** [comment]
I would open a PR in huggingface_hub for this
