### ISSUE TITLE
does not work on WSL ubuntu nor debian

### ISSUE THREAD

**Issue by lucyknada** [huggingface/hf_transfer#22]
### System Info

- WSL2, ubuntu 22.04.3 LTS (and latest available debian but it's not installed anymore on this machine)
- latest pip hf_transfer as of 20th Jan '24 (I can't look up which version I have, if there is an easy way, I'll be happy to provide it)
- windows 11

### Reproduction

1. install hf_transfer via pip inside WSL2
2. enable it for hf-cli
3. try to upload files
4. it gets stuck on 0% forever and can't be killed via ^C

### Expected behavior

1. upload works the same way as on linux and does not get stuck

**Comment by lucyknada** [comment]
Tried just now, progressbar also gets stuck once it reaches the what I assume is LFS stored artifacts, eventually finishes and all files are there but they are 0 bytes each.

It seems to work (incl. latest hf_transfer) if HF_HOME is inside WSL itself, and not on a /mnt/ drive auto-mounted by WSL.

**Comment by Narsil** [comment]
WSL is a bit picky on managing disk files, it's hard to help you. 

I think just writing to WSL owned directory, then moving it on automounted if your best solution.

The reason is possibly that WSL doesn't manage well multi-threaded partial writes outside its partition
