### ISSUE TITLE
'hf_transfer' does not support `resume_size`: falling back to regular download method

### ISSUE THREAD

**Issue by higis927** [huggingface/hf_transfer#28]
I installed hf_transfer hf_transfer-0.1.6; huggingface_hub version: 0.21.3 on MAC
I enabled hf_transfer, and ran huggingface-cli download, the warning is fired as following and it seems hf_transfer does not work.
What should I do to make hf_transfer work? 
=================
 huggingface-cli download --resume-download TheBloke/Yi-34B-200K-GGUF yi-34b-200k.Q2_K.gguf --local-dir .
downloading https://hf-mirror.com/TheBloke/Yi-34B-200K-GGUF/resolve/main/yi-34b-200k.Q2_K.gguf to /Users/sunyan/.cache/huggingface/hub/models--TheBloke--Yi-34B-200K-GGUF/blobs/e5c8cc4d4d5801707e0e98f1f974c5d2661de95491fc976975c5a855211291d7.incomplete
/Users/sunyan/miniconda3/lib/python3.9/site-packages/huggingface_hub/file_download.py:453: UserWarning: 'hf_transfer' does not support `resume_size`: falling back to regular download method
  warnings.warn("'hf_transfer' does not support `resume_size`: falling back to regular download method")

**Comment by Wauplin** [comment]
Hi @higis927, sorry for the inconvenience and for the late response. This warning tells you that `hf_transfer` can't resume from a previous download (because of how it's built internally). What you can do is delete this file and restart the download:

```
# delete incomplete download
rm /Users/sunyan/.cache/huggingface/hub/models--TheBloke--Yi-34B-200K-GGUF/blobs/e5c8cc4d4d5801707e0e98f1f974c5d2661de95491fc976975c5a855211291d7.incomplete

# restart from scratch
huggingface-cli download --resume-download TheBloke/Yi-34B-200K-GGUF yi-34b-200k.Q2_K.gguf --local-dir .
```
