### ISSUE TITLE
MacOS: Installation in Python 3.9.19 requires Cargo to be installed

### ISSUE THREAD

**Issue by Andrei-Aksionov** [huggingface/hf_transfer#33]
### System Info

> [!Important]
> The issue only exists in MacOS

Hi there 👋 

If I want to install `hf-transfer` (0.1.6) in a venv with Python 3.9.19 I have such an error:
```python
Collecting hf-transfer
  Using cached hf_transfer-0.1.6.tar.gz (22 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      
      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/
      
      Checking for Rust toolchain....
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

If I do the same with Python 3.8, 3.10, 3.11 or Python 3.9 but `hf-transfer==0.1.4` I don't have any issue. 

### Reproduction

1. Create a venv with Python 3.9.19
2. pip install hf-transfer

### Expected behavior

Installation doesn't build a wheel, but rather installs a pre-build one.

**Comment by McPatate** [comment]
Could you share more information about the platform you are running this on? We might not pre-build binaries for your system.

**Comment by Andrei-Aksionov** [comment]
Hey @McPatate 
Sorry for the late response.

> Could you share more information about the platform you are running this on?

Python 3.9 on a MacOS.
I even highlighted it at the very top of the issue 😊.

Now the issue is resolved. I can install it in a venv with 3.9.19 on MacOS.
And the necessary files exist on [PyPI page](https://pypi.org/project/hf-transfer/#files)
<img width="925" alt="Screenshot 2024-07-28 at 5 17 14 PM" src="https://github.com/user-attachments/assets/e2008300-536e-48ea-b47c-796150dde545">


Closing.
