### ISSUE TITLE
`HF_ENDPOINT` not take effect when `HF_HUB_ENABLE_HF_TRANSFER=1` enabled

### ISSUE THREAD

**Issue by Mon-ius** [huggingface/hf_transfer#34]
### System Info

python3.12
huggingface_hub v0.23.0

### Reproduction

HF_ENDPOINT="https://mirrorxxxxx.com" HF_HUB_ENABLE_HF_TRANSFER=1 huggingface-cli download $ORG/$DATA --include "*.parquet" --repo-type dataset --token xxxxxxx

### Expected behavior

work as no `HF_HUB_ENABLE_HF_TRANSFER=1` enabled

**Comment by McPatate** [comment]
I think this should live in https://github.com/huggingface/huggingface_hub.

**Comment by McPatate** [comment]
Can you explain in more detail what the issue is please?
