### ISSUE TITLE
Any way to limit upload speeds?

### ISSUE THREAD

**Issue by bartowski1182** [huggingface/hf_transfer#36]
hf_transfer is SO efficient that it actually completely clogs my bandwidth and makes me unable to maintain SSH connections.. Is there any way we can add a cap on up/download speeds? I know probably a niche request..

**Comment by McPatate** [comment]
Try playing around w/ the `max_files` parameter. `max_files` controls the # of concurrent downloads, so reducing that should reduce bandwidth.
Lmk if that works for you and feel free to close the issue if so :)

**Comment by bartowski1182** [comment]
thank you i'll give that a shot! Is it possible to pass this parameter when using huggingface-cli with the HF_HUB_ENABLE_HF_TRANSFER=1 environment variable?

**Comment by McPatate** [comment]
There is a [constant](https://github.com/huggingface/huggingface_hub/blob/a24f7d6b9868ce6c3a656e8511ac32dc9de82a21/src/huggingface_hub/constants.py#L38) in `huggingface_hub` called `HF_TRANSFER_CONCURRENCY`. I think the only way would be to monkey patch it before calling the upload/download function.
