### ISSUE TITLE
hf_transfer stopped uploading suddenly.

### ISSUE THREAD

**Issue by PsilAxis** [huggingface/hf_transfer#37]
While uploading a model to huggingface, HF_Transfer took up all of my bandwidth, i was practically unable to use the internet. 

However, after a while i noticed that the network usage was back down to 0 and my upload had stopped entirely. The model was not uploaded into the repository.

cntrl + c did not work to interrupt and had to close terminal entirely.

**Comment by Larryvrh** [comment]
It seems like due to huggingface's unpredictable rate limit as mentioned in #30, I did a ugly but seemly working monkey patch to temporarily alleviate it by manually limit the concurrency.
```python
huggingface_hub.constants.HF_TRANSFER_CONCURRENCY = 16
original_upload = hf_transfer.multipart_upload
def patched_upload(*args, callback=None, **kwargs):
    kwargs['max_files'] = huggingface_hub.constants.HF_TRANSFER_CONCURRENCY
    kwargs['parallel_failures'] = kwargs['max_files'] - 1
    kwargs['callback'] = callback
    result = original_upload(*args, **kwargs)
    return result
hf_transfer.multipart_upload = patched_upload
```

**Comment by Narsil** [comment]
Are you using it from a personal network ?

It shouldn't really be used on personal network as the hardware is not really made for that.
That being said there might be a deadlock somewhere that was triggered here, we'll look into it.

**Comment by Narsil** [comment]
I found and fixed 1 GIL deadlock that was happening in the tight loop (python errors are apparently taking the GIL).

It was kind of inconisistent to trigger though. Newer version will fix it.
