### ISSUE TITLE
[Question] Uploadibg datset on HF through command-line CLI for hf_transfer

### ISSUE THREAD

**Issue by sleepingcat4** [huggingface/hf_transfer#47]
I have been getting stuck with uploading my dataset on HF using Huggingface hub today. Like it's not uploading and getting stuck in a freeze condition. I raised on issue on HF discord. Meanwhile I was thinking of using hf_transfer. 

I couldn't find any command or method to upload datasets using HF transfer using command line CLI. I tried writing commands like 

```huggingface-cli upload laion/Wikipedia_11_23_BGE-M3_Embeddings enwikientire.parquet.gz --repo-type dataset```

and 

```hf_transfer/hf-transfer upload laion/Wikipedia_11_23_BGE-M3_Embeddings enwikientire.parquet.gz --repo-type dataset``` and nothing happens except saying comamnd not found. 

is there anything i'm missing?

refer
-----------
https://huggingface.co/docs/huggingface_hub/v0.24.5/package_reference/environment_variables#hfhubenablehftransfer

**Comment by julien-c** [comment]
cc @Wauplin :)

**Comment by Wauplin** [comment]
Hi @sleepingcat4, hf_transfer is meant to speed-up upload on machines with large bandwidth. If you are stuck in a regular upload, it's best to open an issue on the `huggingface_hub` repo with more details about where it gets stuck. If you are uploading a very large folder (which seems to be the case), you might be interested in our on-going work in https://github.com/huggingface/huggingface_hub/pull/2254. It's not merged yet but it has been extensively tested already. You can find more details in the PR description.

**Comment by sleepingcat4** [comment]
@Wauplin thanks! I was looking for both. Like shifting to HF transfer completely. Since I have to upload upto 10T datasets pretty often. Btw is there a way to increase the upload size? I was requesting for LAION. If you guys could increase the upload size for LAION AI org, we could upload datasets quite easily. 

At the moment our upload size: 50GB

**Comment by Wauplin** [comment]
> Since I have to upload upto 10T datasets pretty often.

Could you share more about the dataset you are uploading? What is it about and how will it be beneficial to end users? Asking because several datasets of 10T each is a lot of data to store :hugs: 

 > If you guys could increase the upload size for LAION AI org, we could upload datasets quite easily.
> At the moment our upload size: 50GB

The "50GB per file" limit is a hard-limit on the Hub and cannot be lifted. We usually advice to chunk the dataset in smaller files (5-10GB). Here is a guide with limits and recommendations: https://huggingface.co/docs/hub/repositories-recommendations.

**Comment by sleepingcat4** [comment]
> Could you share more about the dataset you are uploading? What is it about and how will it be beneficial to end users? Asking because several datasets of 10T each is a lot of data to store 🤗

Hahah sure! I think you already know who are the intended audience of LAION AI's datasets. But for the on-going project where we are working on for creating something between 5-15T dataset, we are making this to open a new genre of artificial intelligence models and create our open assistant. 

Btw we know several 10T datasets can be too much for HF to handle. That's why, we are planning to shift some of those datasets' release completely from university storage clusters than hosting it on HF.

**Comment by Wauplin** [comment]
Great! Thanks for the details. Should we close the issue now or is there a missing topic from your side?
