### ISSUE TITLE
Feature Request: Support proxies with hf_transfer

### ISSUE THREAD

**Issue by vaibhavjindal** [huggingface/hf_transfer#51]
**Description**: Currently, `hf_transfer` does not support the use of proxies when downloading files from the Hugging Face Hub. When attempting to use a proxy, the `huggingface_hub` library raises a warning and fails to import, as indicated by this code snippet: [file_download.py#L353](https://github.com/huggingface/huggingface_hub/blob/51b866f1ad6513b51899aa037ee12d76600b00af/src/huggingface_hub/file_download.py#L353).

**Use Case**: In environments where internet access is restricted or only available through proxies (e.g., corporate networks or secure environments).

**Expected Behavior**: It would be very helpful if `hf_transfer` could be made proxy-compatible, preferably by respecting the standard proxy environment variables (like `HTTP_PROXY`, `HTTPS_PROXY`) or by adding explicit proxy configuration options to the function.

Thank you for considering this enhancement!

**Comment by Narsil** [comment]
The environment variable are supported by reqwest: https://docs.rs/reqwest/0.12.9/reqwest/index.html#proxies

However we have no intent of having a custom made API for proxies. 
Please see our disclaimer
https://github.com/huggingface/hf_transfer/?tab=readme-ov-file#disclaimer
