### ISSUE TITLE
HF_HUB_ENABLE_HF_TRANSFER is not working on Kaggle

### ISSUE THREAD

**Issue by FurkanGozukara** [huggingface/hf_transfer#53]
free Kaggle account notebook

Here so simple code to test. Download is still limited 40 MB. When it works it gets over 300 MB per second

```
!pip install huggingface_hub hf_transfer     

from huggingface_hub import snapshot_download
!export HF_HUB_ENABLE_HF_TRANSFER=1
import os
os.environ['HF_HUB_ENABLE_HF_TRANSFER'] = '1'

snapshot_download(
            repo_id="Efficient-Large-Model/Sana_1600M_1024px",
            allow_patterns="*/Sana_1600M_1024px.pth",
            local_dir=f"models"
        )
        
snapshot_download(
            repo_id="Efficient-Large-Model/Sana_1600M_2Kpx_BF16",
            allow_patterns="*/Sana_1600M_2Kpx_BF16.pth",
            local_dir=f"models"
        )  
```

![image](https://github.com/user-attachments/assets/00eaeab7-9a8b-473c-9afc-72b9ec999427)

**Comment by Narsil** [comment]
You are importing huggingface_hub before setting your environement variable.

Swap out the 2 if you want to make it work.
Also if you're in an environment you are not in control of, a lot of limitations might be applied by the host which can affect your download speeds (outside of this lib's control)

**Comment by FurkanGozukara** [comment]
> You are importing huggingface_hub before setting your environement variable.
> 
> Swap out the 2 if you want to make it work. Also if you're in an environment you are not in control of, a lot of limitations might be applied by the host which can affect your download speeds (outside of this lib's control)

thanks a lot that makes sense
